### ISSUE TITLE
task: Implement standard IE function in rust

### ISSUE THREAD

**Issue by IdoDesign** [DeanLight/spannerflow#11]
Write in rust all IE function possible in rust
List defined here: https://deanlight.github.io/spannerlib/tutorials/introduction.html

**Comment by IdoDesign** [comment]
Hi @DeanLight,
 Can you refer us to the regex and span libraries in rust that you suggested we use for this part?

**Comment by DeanLight** [comment]
There was no span library, but [this regex library](https://github.com/PoDMR/enum-spanner-rs) supports returning the span indexes of matches rather than the substrings.

**Comment by IdoDesign** [comment]
I tried using this tool but when I tried passing it the pattern from the basic example (\w+) that suppose to return all words in the text, it returned all the substrings in each word instead of only the full word.
I tried to look if it something in the options I can change but I couldn't figure this one out

**Comment by DeanLight** [comment]
@IdoDesign 
In that case, try using rust's regular regex library https://docs.rs/regex/1.1.6/regex/#syntax

Their library seems to support span indices via a `CaptureLocation` struct which you can use to build the span from.
