### ISSUE TITLE
Span Comparison Equality

### ISSUE THREAD

**Issue by IdoDesign** [DeanLight/spannerflow#14]
@DeanLight I wanted to check with you on comparing Spans
in python you compared by comparing also the strings:
```py
def __eq__(self, value: object) -> bool:
        if isinstance(value, Span):
            return self.start == value.start and self.end == value.end and self.doc == value.doc
        elif isinstance(value, str):
            return self.as_str() == value
        else:
            return False
```

Since we are using pointers, how should I check if both spans are equals? imagine that we get spans from python and we want to compare them to what is already in our collection or as intermidiate result.
in that situation I don't think comparing the pointers will work. this is my current code:
```rust
pub struct Span {
    doc: Arc<str>,
    start: usize,
    end: usize,
    name: String,
}

should we compare names? or the sliced strings (meaning doc[start..end])?

impl<'a> PartialEq for Span {
    fn eq(&self, other: &Self) -> bool {
        self.start == other.start && self.end == other.end && self.doc == other.doc
    }
}
```

**Comment by DeanLight** [comment]
We should compare their `(id,start,end)` since they should have the same id, right?

**Comment by IdoDesign** [comment]
by id you mean the 'name' attribute?

**Comment by DeanLight** [comment]
No, i meant the sha1 of the document, the thing you print first in the span.
Although, we could also use the name and have it be the sha1 by default. This could allow a user to give his own id from the outside and have it be used by the system.

**Comment by IdoDesign** [comment]
That's what I meant. in the Span class in spannerlib you have a name which is the sha1 if not given any other name.

**Comment by DeanLight** [comment]
Oh than yes. So in that case you do equality on `(name,start,end)`
