### ISSUE TITLE
Match groups in regex

### ISSUE THREAD

**Issue by IdoDesign** [DeanLight/spannerflow#15]
When using the regex function, given a pattern parameter that might result multiple match groups, for example:
`"(\w+).*?(\d+)"` results 2 groups for the input "abigail 100 jordan 80 gale 79 howard 60" we have 2 match groups.
How do we know in the graph how much match groups will be the result? is it the out_arity? do we have a mechanism to check the out- arity is correct?

**Comment by DeanLight** [comment]
We know how many groups we expect based on the schema in the graph, which is derived from how the spannercode was written.
From the out/in arity function, we derive the types of the of the output/input given the arity they are given in the spannerlog code.

However, it is possible that the tuple that we got in practice, is of a different schema that what we expected. This would be a runtime error.

You can see how we check for it now in nb 008 under the helper functions for `ie_map`.
