### ISSUE TITLE
bug: Mutual dependencies

### ISSUE THREAD

**Issue by techofer** [DeanLight/spannerflow#2]
We faced an issue:
we are recieving a theta objects and we need determine if it's  equalConstTheta or equalColTheta but we can't import spannerlib as spannerflow is going to be it's depency.

suggestion: having third library that is going to be requried by both modules

**Comment by DeanLight** [comment]
Dont have the schema of your graph be dependant on external datatypes.
Make your own schema. you can encode it as primitives.

for example:
```
{
'op':'select',
'select_type':'constant',
'lhs':['col1','col2'],
'rhs':[1,'hello']
}

```


If you need objects to describe it, you can write them in Spannerflow.

**Comment by techofer** [comment]
Dont we have similar issue with the Spaner class? I guess we need it in our python as well

**Comment by DeanLight** [comment]
Yeah, That makes sense.
So you can put the span class in spannerflow in python and use it from spannerlib.

**Comment by IdoDesign** [comment]
You mean moving the Span class source code to spannerflow, and in spannerlib import Span from spannerflow?
 (and we can do the same for Theta I think)

**Comment by DeanLight** [comment]
For span for sure, as it pertains to data passing between the rust and python.
For theta you need to see if it warrants the interface extension (as opposed to simply extending the json schema you support for the graph), but in principle yes.

**Comment by IdoDesign** [comment]
I changed spannerlib to import Span from spannerflow.
