### ISSUE TITLE
question: fact mismatch relation schema

### ISSUE THREAD

**Issue by techofer** [DeanLight/spannerflow#26]
Hi,
I came across this issue running 020_micro_passes.ipynb (spannerlib)

as you can see in the attached screenshot, this test define relation R with schema [str, int]
and then try to add fact with types [span, int].
therefore this test failed.
my question is what should we do? should adjust the test?

<img width="935" alt="image" src="https://github.com/user-attachments/assets/485d1351-cc04-40cb-8c91-edd5052bc7d2">

**Comment by DeanLight** [comment]
In the old implementation, a Span was an instance of a string and could ducktype as one.
In your implementation, as I understand, this is not possible and so you should change the test.
