### ISSUE TITLE
question: return_intermediate

### ISSUE THREAD

**Issue by techofer** [DeanLight/spannerflow#28]
came across this issue while running 010_engine.ipynb (spannerlib).

the question how should we adjust tests using return_intermediate as the behaviour changed

<img width="935" alt="image" src="https://github.com/user-attachments/assets/f6c34b87-69d9-4745-b13a-f88ac2a25035">

**Comment by DeanLight** [comment]
You dont have to support the get_intermediate flag.

It was simply a debugging utility.
You can get rid of it in spannerlib so long that spannerflow has a "trace" mode where it outputs intermediate results to a log file or something.
