### ISSUE TITLE
bug: document registry on server and library are not the same

### ISSUE THREAD

**Issue by techofer** [DeanLight/spannerflow#32]
current situation:

- span and registry are together on rust_span, compiled as static library and linked to both server and rust_lib (timely).
- we manage to add spans via import_rel (server), but we can't get them on query (rust_lib). 
we believe that although it's the same runtime there are two instances of the registry.

this will be the main topic to discuss on Monday.

**Comment by IdoDesign** [comment]
Solved- The problem was related to de-serializing subspans  in python from registry by keeping aside from the start and end of the span, the start and end of the string for this specific object
