### ISSUE TITLE
Span-rgx look back out of the span

### ISSUE THREAD

**Issue by IdoDesign** [DeanLight/spannerflow#33]
Given a pattern, and a span, should the regex look at the entire document or just in the (start, end) range? this was not defined in the docs and we might think that might cause the issues we seen, for example this is code that we ran on the master branch:

![WhatsApp Image 2024-12-15 at 22 37 10](https://github.com/user-attachments/assets/81e45cdb-15cf-4e4f-a7a3-229120eed191)

**Comment by DeanLight** [comment]
rgx should look at the text it was given. If it was given a span, it should only look at the string of the span, not the entire document.

This is so that you can nest rgx calls on output of other rgx calls.
